### ISSUE TITLE
Figma - Design UX 

### ISSUE THREAD

**Issue by BillyMerchan** [BillyMerchan/Libre#10]
Design a UX using figma to get a good idea for the frontend.

**Comment by electo2022** [comment]
I am proficient in Figma and would like to contribute and assist you with this issue.

**Comment by BillyMerchan** [comment]
Sounds great, totally willing to accept any help offered.  If you have any questions feel free to reach out and I can help as much as possible!

**Comment by electo2022** [comment]
perfect, Do you have any examples of what you want to achieve on the front end, or any links from which I can get ideas a ux in figma?

**Comment by BillyMerchan** [comment]
A few sparse ideas, but please feel free to adjust ideas as you see fit as the structure is very tentative. The main vision we had for a front end theme is something minimalist and streamlined like the websites below:
- https://slite.com/
- https://ready.so/
Front end navigation would have a home page outlining what Libre is as a service, an area to contact developers, a quick FAQ, and a Sign-In/Sign-Up link.
Additionally a separate page with a "map" of room layouts that is displayed when signed in.
Lastly a page that appears when scanning a QR Code in the study room you are occupying - something simple prompting the user to check-in/check-out and easily accessible on mobile.

Thank you again, I'll be routinely checking the repo if you have any other concerns :)

**Comment by electo2022** [comment]
I reviewed the example websites as inspiration for what you are seeking and have some new ideas; please assign me to this issue so that I can go to work on it ))

**Comment by BillyMerchan** [comment]
On it!

**Comment by electo2022** [comment]
Thanks, will be working on it and keep you updated.

**Comment by electo2022** [comment]
I made a prototype and a pull request; if you didn't see it, please check the link below and let me know how to commit the issue.

https://www.figma.com/proto/TP7KwdfvImCRUsNIgLJSYI/Libre?page-id=0%3A1&node-id=22%3A1886&viewport=380%2C320%2C0.48&scaling=min-zoom&starting-point-node-id=22%3A1886

**Comment by electo2022** [comment]
I responded to your feedback on the figma prototype; please let me know what steps you would like to take next.

**Comment by BillyMerchan** [comment]
Got it, everything looks great, it would be much appreciated if you could work on designing the ux for the navbar pages. The sign-in/sign-up, FAQ, and developer contact pages. Other than that, I would greatly appreciate any recommendations for color themes / typefaces. Thank you again for contributing!

**Comment by electo2022** [comment]
I would suggest closing the issue for "Figma - design ux" and then I can create 3 separate issues for each of the FAQ, Sign in and Developers pages and take on them one by one as we go ahead
When all pages are completed and the layout is determined, we can move on to the face type and colour theme.

**Comment by BillyMerchan** [comment]
Got it sounds good!
