### ISSUE TITLE
Signin/Signup Page Design

### ISSUE THREAD

**Issue by electo2022** [BillyMerchan/Libre#28]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by electo2022** [comment]
I've just added Sign in and Sign up pages to the prototype; please take a look and let me know what you think.

https://www.figma.com/proto/TP7KwdfvImCRUsNIgLJSYI/Libre?page-id=0%3A1&node-id=22%3A1886&viewport=-990%2C401%2C0.63&scaling=min-zoom&starting-point-node-id=22%3A1886

**Comment by BillyMerchan** [comment]
Looks good, had a few comments that I added but other than that very nice simple ux.

**Comment by BillyMerchan** [comment]
Gotcha, looks good!
