### ISSUE TITLE
FAQ Page Design

### ISSUE THREAD

**Issue by BillyMerchan** [BillyMerchan/Libre#29]
**Describe the solution you'd like**
Figma design of the FAQ page with a viewable link

**Comment by electo2022** [comment]
I am going to work on this page, can you tell me a little bit about whats going to be here?

**Comment by BillyMerchan** [comment]
Hey, sorry to get back to you so late, was crunch time for me at uni.

I mainly wanted this page to be a guide for new users, a few starting questions asking how to use and navigate the website. There are not a whole lot of other requisites so feel free to take creative freedom.

**Comment by electo2022** [comment]
oh it's okay, no worries
I have created a FAQ Page with questions and answers that I believe are connected; please have a look and let me know what you think.

**Comment by BillyMerchan** [comment]
Okay I took a look and everything seems great! Should be good to close.
